require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'vendor/**/*'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'lib/imagemaster3000/cli.rb'

Metrics/LineLength:
  Max: 135

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'lib/imagemaster3000/entities/image.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 3

Metrics/ParameterLists:
  Exclude:
    - 'lib/imagemaster3000/entities/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'
